export const moduleConfigs = {
  sales: {
    title: "Sales Management", description: "Manage quotations, sales orders, invoices, returns, and customer payments.",
    primaryAction: "Create invoice", tabs: ["Invoices", "Quotations", "Sales orders", "Returns"],
    metrics: [["Total sales", "₹8,42,500"], ["Receivables", "₹1,46,800"], ["Paid invoices", "84"], ["Overdue", "8"]],
    columns: ["Document", "Customer", "Date", "Amount", "Status"],
    rows: [["INV-00128", "Aurora Foods", "06 Sep 2026", "₹54,800", "Paid"], ["INV-00127", "Nova Traders", "05 Sep 2026", "₹42,000", "Partial"], ["INV-00126", "Cedar Kitchens", "03 Sep 2026", "₹78,600", "Overdue"], ["INV-00125", "Urban Bakehouse", "01 Sep 2026", "₹31,200", "Unpaid"]],
  },
  purchases: {
    title: "Purchase Management", description: "Track purchase orders, supplier bills, returns, and supplier payments.",
    primaryAction: "Create purchase order", tabs: ["Purchase orders", "Bills", "Returns", "Payments"],
    metrics: [["Total purchases", "₹4,06,900"], ["Payables", "₹92,300"], ["Open orders", "14"], ["Due bills", "6"]],
    columns: ["Document", "Supplier", "Date", "Amount", "Status"],
    rows: [["PO-0048", "Metro Steel Works", "06 Sep 2026", "₹82,400", "Received"], ["PO-0047", "Prime Components", "05 Sep 2026", "₹46,700", "Ordered"], ["BILL-0092", "HeatPro Systems", "02 Sep 2026", "₹64,200", "Unpaid"], ["PO-0046", "Royal Fabrication", "29 Aug 2026", "₹29,600", "Partial"]],
  },
  inventory: {
    title: "Inventory Management", description: "Monitor current stock, stock movements, adjustments, and low-stock items.",
    primaryAction: "Stock adjustment", tabs: ["Current stock", "Transactions", "Low stock", "Adjustments"],
    metrics: [["Stock value", "₹12,84,600"], ["Total items", "186"], ["Low stock", "9"], ["Out of stock", "3"]],
    columns: ["SKU", "Product", "Category", "Current stock", "Status"],
    rows: [["OVN-EL-02", "Electric Baking Oven", "Ovens", "12 pcs", "In stock"], ["FRY-GS-04", "Gas Deep Fryer", "Fryers", "4 pcs", "Low stock"], ["RCK-SS-08", "Stainless Steel Rack", "Fabrication", "0 pcs", "Out of stock"], ["MIX-PL-03", "Planetary Mixer", "Bakery", "18 pcs", "In stock"]],
  },
  customers: {
    title: "Customer Management", description: "View customer contacts, sales history, and outstanding balances.",
    primaryAction: "Add customer", tabs: ["All customers", "Outstanding", "Inactive"],
    metrics: [["Total customers", "248"], ["Active", "231"], ["Outstanding", "₹1,46,800"], ["New this month", "18"]],
    columns: ["Customer", "Contact", "Total sales", "Outstanding", "Status"],
    rows: [["Aurora Foods", "+91 98765 43210", "₹2,84,000", "₹0", "Active"], ["Nova Traders", "+91 98470 22119", "₹1,46,500", "₹21,000", "Active"], ["Cedar Kitchens", "+91 79075 48211", "₹98,600", "₹78,600", "Outstanding"], ["Urban Bakehouse", "+91 96052 18830", "₹76,200", "₹31,200", "Active"]],
  },
  suppliers: {
    title: "Supplier Management", description: "Maintain supplier records, purchase history, and amounts payable.",
    primaryAction: "Add supplier", tabs: ["All suppliers", "Amount payable", "Inactive"],
    metrics: [["Total suppliers", "42"], ["Active", "38"], ["Amount payable", "₹92,300"], ["Purchases", "₹4,06,900"]],
    columns: ["Supplier", "Contact", "Purchases", "Payable", "Status"],
    rows: [["Metro Steel Works", "+91 98460 11220", "₹1,82,400", "₹0", "Active"], ["Prime Components", "+91 99471 32008", "₹96,700", "₹46,700", "Payable"], ["HeatPro Systems", "+91 80752 91460", "₹84,200", "₹45,600", "Payable"], ["Royal Fabrication", "+91 81294 77182", "₹43,600", "₹0", "Active"]],
  },
  products: {
    title: "Products & Items", description: "Manage product and service masters, SKU, prices, categories, and tax information.",
    primaryAction: "Add item", tabs: ["Products", "Services", "Categories"],
    metrics: [["Products", "174"], ["Services", "12"], ["Categories", "16"], ["Taxable items", "168"]],
    columns: ["SKU / Code", "Item", "Category", "Cost / Selling", "Tax"],
    rows: [["OVN-EL-02", "Electric Baking Oven", "Ovens", "₹28,000 / ₹42,000", "18%"], ["FRY-GS-04", "Gas Deep Fryer", "Fryers", "₹16,800 / ₹25,900", "18%"], ["RCK-SS-08", "Stainless Steel Rack", "Fabrication", "₹7,200 / ₹11,500", "18%"], ["SRV-INST", "Installation Service", "Services", "₹0 / ₹4,500", "18%"]],
  },
  expenses: {
    title: "Expense Management", description: "Record expenses, organize categories, and review payment history.",
    primaryAction: "Record expense", tabs: ["All expenses", "Categories", "Recurring"],
    metrics: [["This month", "₹3,18,200"], ["Today", "₹12,400"], ["Categories", "11"], ["Cash expenses", "₹48,900"]],
    columns: ["Expense", "Category", "Date", "Amount", "Payment method"],
    rows: [["Office rent", "Rent", "01 Sep 2026", "₹48,000", "Bank transfer"], ["Software subscription", "Software", "04 Sep 2026", "₹4,900", "Card"], ["Delivery fuel", "Travel", "05 Sep 2026", "₹3,200", "Cash"], ["Digital campaign", "Marketing", "06 Sep 2026", "₹18,000", "UPI"]],
  },
  accounting: {
    title: "Basic Accounting", description: "Review income, expenses, receivables, payables, and cash or bank transactions.",
    primaryAction: "Add transaction", tabs: ["Overview", "Cash & bank", "Receivables", "Payables", "Profit & loss"],
    metrics: [["Income", "₹8,42,500"], ["Expenses", "₹3,18,200"], ["Receivables", "₹1,46,800"], ["Payables", "₹92,300"]],
    columns: ["Transaction", "Account", "Date", "Amount", "Type"],
    rows: [["Invoice payment INV-00128", "Main Bank", "06 Sep 2026", "₹54,800", "Income"], ["Purchase payment BILL-0090", "Main Bank", "05 Sep 2026", "₹34,000", "Payment"], ["Delivery fuel", "Cash", "05 Sep 2026", "₹3,200", "Expense"], ["Customer advance", "Main Bank", "04 Sep 2026", "₹25,000", "Income"]],
  },
  reports: {
    title: "ERP Reports", description: "Analyze sales, purchases, inventory, expenses, balances, and profit or loss.",
    primaryAction: "Export report", tabs: ["Sales", "Purchases", "Inventory", "Expenses", "Balances", "Profit & loss"],
    metrics: [["Sales", "₹8,42,500"], ["Purchases", "₹4,06,900"], ["Expenses", "₹3,18,200"], ["Net profit", "₹2,17,400"]],
    columns: ["Report", "Period", "Records", "Total", "Action"],
    rows: [["Sales report", "This month", "96", "₹8,42,500", "View"], ["Purchase report", "This month", "38", "₹4,06,900", "View"], ["Inventory report", "Current", "186", "₹12,84,600", "View"], ["Profit & loss", "This month", "—", "₹2,17,400", "View"]],
  },
  users: {
    title: "Users & Roles", description: "Manage Admin and staff accounts with role-based view, edit, and delete permissions.",
    primaryAction: "Add user", tabs: ["Users", "Roles", "Permissions"],
    metrics: [["Total users", "14"], ["Admins", "2"], ["Staff", "11"], ["Inactive", "1"]],
    columns: ["User", "Email", "Role", "Last login", "Status"],
    rows: [["System Admin", "admin@example.com", "Admin", "Today, 9:42 AM", "Active"], ["Nisha", "nisha@example.com", "Sales staff", "Today, 8:20 AM", "Active"], ["Anoob", "anoob@example.com", "Purchase staff", "Yesterday", "Active"], ["Safa", "safa@example.com", "Accountant", "03 Sep 2026", "Inactive"]],
  },
  settings: {
    title: "System Settings", description: "Configure company details, tax, currency, invoice numbering, backup, and data export.",
    primaryAction: "Save settings", tabs: ["Company", "Tax & currency", "Numbering", "Backup & export"],
    metrics: [["Currency", "INR (₹)"], ["Default tax", "18% GST"], ["Invoice prefix", "INV"], ["Last backup", "06 Sep 2026"]],
    columns: ["Setting", "Current value", "Category", "Updated", "Status"],
    rows: [["Company profile", "CRM Business", "Company", "01 Sep 2026", "Configured"], ["GST", "18%", "Tax", "01 Sep 2026", "Active"], ["Invoice numbering", "INV-000001", "Documents", "04 Sep 2026", "Active"], ["Automatic backup", "Daily", "Data", "06 Sep 2026", "Enabled"]],
  },
};
